plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
}

group = 'fox'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    String jUnitVersion = '5.14.4'

    testImplementation "org.junit.jupiter:junit-jupiter-api:${jUnitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${jUnitVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

application {
    mainClass = 'fox.Fox'
}

def foxTestClasses = [
        'fox.parser.TaskParserTest',
        'fox.storage.StorageTest',
        'fox.task.TaskListTest',
        'fox.FoxPersistenceTest'
]

test {
    useJUnitPlatform()
    failOnNoDiscoveredTests = false

    testLogging {
        events 'passed', 'skipped', 'failed'
        showExceptions = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }

    doLast {
        foxTestClasses.each { testClass ->
            logger.lifecycle("Running Fox test ${testClass}")
            project.javaexec {
                classpath = sourceSets.test.runtimeClasspath
                mainClass = testClass
                enableAssertions = true
            }
        }
    }
}

jar {
    enabled = false
    archiveClassifier = 'without-dependencies'
}

shadowJar {
    archiveFileName = 'fox.jar'
}

run {
    standardInput = System.in
}
